name       : sdl2-image
version    : 2.0.1
release    : 5
source     :
    - https://www.libsdl.org/projects/SDL_image/release/SDL2_image-2.0.1.tar.gz : 3a3eafbceea5125c04be585373bfd8b3a18f259bd7eae3efc4e6d8e60e0d7f64
license    : Zlib
component  : multimedia.library
summary    : SDL_image is an image file loading library.
description: |
    SDL_image is an image file loading library.
emul32     : yes
optimize   : speed
builddeps  :
    - pkgconfig32(libpng)
    - pkgconfig32(libtiff-4)
    - pkgconfig32(libwebp)
    - pkgconfig32(sdl2)
    - pkgconfig32(zlib)
    - libjpeg-turbo-32bit-devel
setup      : |
    %patch -p1 < $pkgfiles/security/cve-2017-2887.patch
    %configure --disable-static --prefix=/usr
build      : |
    %make
install    : |
    %make_install
