name       : sdl2-image
version    : 2.0.0
release    : 1
source     :
    - https://www.libsdl.org/projects/SDL_image/release/SDL2_image-2.0.0.tar.gz : b29815c73b17633baca9f07113e8ac476ae66412dec0d29a5045825c27a47234
license    : Zlib
summary    : SDL_image is an image file loading library.
description: |
    SDL_image is an image file loading library.
builddeps  :
    - pkgconfig(libpng)
    - pkgconfig(libtiff-4)
    - libjpeg-turbo-devel
    - pkgconfig(libwebp)
    - pkgconfig(sdl2)
setup      : |
    %configure --disable-static
build      : |
    %make
install    : |
    %make_install
