name       : sdl2-image
version    : 2.0.1
release    : 4
source     :
    - https://www.libsdl.org/projects/SDL_image/release/SDL2_image-2.0.1.tar.gz : 3a3eafbceea5125c04be585373bfd8b3a18f259bd7eae3efc4e6d8e60e0d7f64
license    : Zlib
component  : multimedia.library
summary    : SDL_image is an image file loading library.
description: |
    SDL_image is an image file loading library.
builddeps  :
    - pkgconfig(libpng)
    - pkgconfig32(libpng)
    - pkgconfig32(zlib)
    - pkgconfig(libtiff-4)
    - pkgconfig32(libtiff-4)
    - libjpeg-turbo-devel
    - libjpeg-turbo-32bit-devel
    - pkgconfig(libwebp)
    - pkgconfig32(libwebp)
    - pkgconfig(sdl2)
    - pkgconfig32(sdl2)
    - glibc-32bit-devel
    - libgcc-32bit
    - libstdc++-32bit
emul32     : yes
optimize   : speed
setup      : |
    %configure --disable-static --prefix=/usr
build      : |
    %make
install    : |
    %make_install
