name       : sdl2-image
version    : 2.0.0
release    : 2
source     :
    - https://www.libsdl.org/projects/SDL_image/release/SDL2_image-2.0.0.tar.gz : b29815c73b17633baca9f07113e8ac476ae66412dec0d29a5045825c27a47234
license    : Zlib
summary    : SDL_image is an image file loading library.
description: |
    SDL_image is an image file loading library.
builddeps  :
    - pkgconfig(libpng)
    - pkgconfig32(libpng)
    - pkgconfig32(zlib)
    - pkgconfig(libtiff-4)
    - pkgconfig32(libtiff-4)
    - libjpeg-turbo-devel
    - libjpeg-turbo-32bit-devel
    - pkgconfig(libwebp)
    - pkgconfig32(libwebp)
    - pkgconfig(sdl2)
    - pkgconfig32(sdl2)
    - glibc-32bit-devel
    - libgcc-32bit
    - libstdc++-32bit
emul32     : yes
optimize   : speed
setup      : |
    %configure --disable-static --prefix=/usr
build      : |
    %make
install    : |
    %make_install
