name       : sdl2-image
version    : 2.0.5
release    : 10
source     :
    - https://www.libsdl.org/projects/SDL_image/release/SDL2_image-2.0.5.tar.gz : bdd5f6e026682f7d7e1be0b6051b209da2f402a2dd8bd1c4bd9c25ad263108d0
license    : Zlib
component  : multimedia.library
summary    : SDL_image is an image file loading library.
description: |
    SDL_image is an image file loading library.
emul32     : yes
optimize   : speed
builddeps  :
    - pkgconfig32(libturbojpeg)
    - pkgconfig32(libpng)
    - pkgconfig32(libtiff-4)
    - pkgconfig32(libwebp)
    - pkgconfig32(sdl2)
    - pkgconfig32(zlib)
setup      : |
    %configure --disable-static --prefix=/usr
build      : |
    %make
install    : |
    %make_install
