name       : sdl2-image
version    : 2.6.3
release    : 15
source     :
    - https://github.com/libsdl-org/SDL_image/archive/refs/tags/release-2.6.3.tar.gz : e3fb5136e1c0e0e118051fbd96cddaf988715ed9fec9296b4861e21823c75b75
license    : Zlib
component  : multimedia.library
summary    : SDL_image is an image file loading library.
description: |
    SDL_image is an image file loading library.
emul32     : yes
optimize   : speed
builddeps  :
    - pkgconfig32(libjpeg)
    - pkgconfig32(libpng)
    - pkgconfig32(libtiff-4)
    - pkgconfig32(libwebp)
    - pkgconfig32(sdl2)
setup      : |
    %configure \
        --disable-jpg-shared \
        --disable-png-shared \
        --disable-static \
        --disable-stb-image \
        --disable-tif-shared \
        --disable-webp-shared \
        --prefix=/usr
build      : |
    %make
install    : |
    %make_install
