name       : sdl2-image
version    : 2.6.2
release    : 12
source     :
    - https://github.com/libsdl-org/SDL_image/archive/refs/tags/release-2.6.2.tar.gz : 5d91ea72b449a161821ef51464d0767efb6fedf7a773f923c43e483dc137e362
license    : Zlib
component  : multimedia.library
summary    : SDL_image is an image file loading library.
description: |
    SDL_image is an image file loading library.
emul32     : yes
optimize   : speed
builddeps  :
    - pkgconfig32(libturbojpeg)
    - pkgconfig32(libpng)
    - pkgconfig32(libtiff-4)
    - pkgconfig32(libwebp)
    - pkgconfig32(sdl2)
    - pkgconfig32(zlib)
setup      : |
    %configure --disable-static --prefix=/usr
build      : |
    %make
install    : |
    %make_install
